# Generated by Django 2.2 on 2019-07-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190716_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='overview',
            field=models.TextField(default='Enter product overview', max_length=2000),
        ),
        migrations.AddField(
            model_name='product',
            name='per',
            field=models.CharField(default='Enter measurement unit', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(default='Enter product specifications', max_length=2000),
        ),
    ]
