# Generated by Django 2.2 on 2019-07-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190729_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='overview',
            field=models.TextField(default='Enter product overview', max_length=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.TextField(default='Enter product specifications', max_length=8000),
        ),
    ]
