# Generated by Django 2.2 on 2019-07-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'about us', 'verbose_name_plural': 'about us'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'director', 'verbose_name_plural': 'director'},
        ),
        migrations.AlterModelOptions(
            name='why_choose_us',
            options={'verbose_name': 'why choose us', 'verbose_name_plural': 'why choose us'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(upload_to='director/'),
        ),
    ]
